
SELECT 
    s.slotid,
    m.moviename,
    s.slot,
    s."date" AS slot_date,
    h.hallname,
    h.type AS hall_type,
    s.price,
    COUNT(t.ticketid) AS tickets_sold
FROM 
    C##CSE464.slottable s
JOIN 
    C##CSE464.movietable m ON s.movietable_movieid = m.movieid
JOIN 
    C##CSE464.ticket t ON t.slottable_slotid = s.slotid
JOIN
    C##CSE464.halltable h ON s.halltable_hallid = h.hallid
WHERE 
    m.moviename = 'The Dark Knight'
GROUP BY 
    s.slotid, s.slot, s."date", m.moviename, s.price, h.type, h.hallname
ORDER BY 
    s."date", s.slot;




-- Update all movie ratings to 0
UPDATE movietable
SET MOVIERATING = 0;

-- Update all hall ratings to 0
UPDATE halltable
SET rating = 0;

-- Optional: Commit the changes (for Oracle)

drop table ratingtable;
COMMIT;
DELETE FROM ratingtable WHERE rating_id = 100;
INSERT INTO ratingtable (rating_id, movie_rating, hall_ratting, ticket_ticketid)
VALUES (100, 4.5, 4.0, 1);
commit;


UPDATE movietable
    SET movierating = (
        SELECT ROUND(AVG(movie_rating), 1)
        FROM ratingtable r
        JOIN ticket t ON r.ticket_ticketid = t.ticketid
        JOIN slottable s ON t.slottable_slotid = s.slotid
        WHERE s.movietable_movieid = 1
    )
    WHERE movieid = 1;
    commit;
SELECT ROUND(AVG(movie_rating), 1)
        FROM ratingtable r
        JOIN ticket t ON r.ticket_ticketid = t.ticketid
        JOIN slottable s ON t.slottable_slotid = s.slotid
        WHERE s.movietable_movieid = 1;


        CREATE TABLE trigger_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR2(4000),
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM trigger_log;
COMMIT;


SELECT column_name FROM all_tab_columns WHERE table_name = 'SLOTTABLE' AND owner = 'C##CSE464';
DESC C##CSE464.AUDIT_RATINGTABLE;


update  seattable set seatno = 1 
where ticket_ticketid = 31 and seattable.SEATNO = 15;
commit;

update SLOTTABLE set SLOTTABLE.HALLTABLE_HALLID = 10
where SLOTTABLE.SLOTID = 26;
commit;

update SLOTTABLE set SLOTTABLE.price = 100
where SLOTTABLE.SLOTID = 26;
COMMIT;

update C##CSE464.ticket set slottable_slotid = 192
where ticket.ticketid = 109;
commit;