grant create materialized view to c##cse464;

DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE SALES CASCADE CONSTRAINTS;

CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER(10) NOT NULL,
    CATAGORY VARCHAR2(50) NOT NULL,
    PRODUCT_PRICE NUMBER(10,2) NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE SALES (
    ORDER_ID NUMBER(10) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    PRODUCT_ID NUMBER(10) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    QUNATITY NUMBER NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

BEGIN   
    FOR I IN 1..500 LOOP
        INSERT INTO PRODUCTS (PRODUCT_ID, CATAGORY, PRODUCT_PRICE) 
        VALUES (
            I, 
            ROUND(DBMS_RANDOM.VALUE(0, 49)+1),
            ROUND(DBMS_RANDOM.VALUE(0, 499), 2));
    END LOOP;
    COMMIT;
END;
/

SELECT COUNT(*) FROM PRODUCTS;

BEGIN   
    FOR I IN 1..50000 LOOP
        INSERT INTO SALES (ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_DATE, QUNATITY) 
        VALUES (
            I, 
            ROUND(DBMS_RANDOM.VALUE(0, 999), 0) + 1,
            ROUND(DBMS_RANDOM.VALUE(0, 499), 0) + 1,
            TO_DATE('2020-01-01', 'YYYY-MM-DD') + ROUND(DBMS_RANDOM.VALUE(0, 1460), 0),
            ROUND(DBMS_RANDOM.VALUE(0, 99), 0)+1);
    END LOOP;
    COMMIT;
END;

SELECT COUNT(*) FROM SALES;