-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2025-05-28 21:42:15 BDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE halltable (
    hallid   NUMBER NOT NULL,
    hallname VARCHAR2(50),
    location VARCHAR2(100),
    rating   NUMBER,
    type     VARCHAR2(50),
    capasity INTEGER
);

COMMENT ON COLUMN halltable.rating IS
    'for 1 to 10';

ALTER TABLE halltable ADD CONSTRAINT halltable_pk PRIMARY KEY ( hallid );

CREATE TABLE halltable_audit (
    audit_id        INTEGER NOT NULL,
    hallid          INTEGER,
    operation_type  VARCHAR2(100),
    old_hallname    VARCHAR2(200),
    new_hallname    VARCHAR2(200),
    old_location    VARCHAR2(100),
    new_location    VARCHAR2(100),
    old_rating      INTEGER,
    new_rating      INTEGER,
    old_type        VARCHAR2(200),
    new_type        VARCHAR2(200),
    old_capsity     INTEGER,
    new_capsity     INTEGER,
    performed_by    VARCHAR2(200),
    operation_time  TIMESTAMP WITH LOCAL TIME ZONE,
    user_ip_address VARCHAR2(200),
    session_user    VARCHAR2(200),
    host_name       VARCHAR2(200)
);

ALTER TABLE halltable_audit ADD CONSTRAINT halltable_audit_pk PRIMARY KEY ( audit_id );

CREATE TABLE movietable (
    movieid     NUMBER NOT NULL,
    moviename   VARCHAR2(50),
    releasedate DATE,
    genre       VARCHAR2(50),
    movierating NUMBER,
    rating      VARCHAR2(50),
    poster      VARCHAR2(50)
);

COMMENT ON COLUMN movietable.rating IS
    'for parental rating';

COMMENT ON COLUMN movietable.poster IS
    'for poster url';

ALTER TABLE movietable ADD CONSTRAINT movietable_pk PRIMARY KEY ( movieid );

CREATE TABLE movietable_audit (
    audit_id        INTEGER NOT NULL,
    operation_type  VARCHAR2(100),
    movieid         NUMBER,
    old_moviename   VARCHAR2(50),
    new_moviename   VARCHAR2(50),
    old_releasedate DATE,
    new_releasedate DATE,
    new_genre       VARCHAR2(50),
    old_genre       VARCHAR2(50),
    old_movierating NUMBER,
    new_movierating NUMBER,
    old_rating      VARCHAR2(50),
    new_rating      VARCHAR2(50),
    poster          VARCHAR2(50),
    performed_by    VARCHAR2(200),
    operation_time  TIMESTAMP WITH LOCAL TIME ZONE,
    user_ip_address VARCHAR2(200),
    session_user    VARCHAR2(200),
    host_name       VARCHAR2(200)
);

COMMENT ON COLUMN movietable_audit.old_rating IS
    'for parental rating';

COMMENT ON COLUMN movietable_audit.new_rating IS
    'for parental rating';

COMMENT ON COLUMN movietable_audit.poster IS
    'for poster url';

ALTER TABLE movietable_audit ADD CONSTRAINT movietable_audit_pk PRIMARY KEY ( audit_id );

CREATE TABLE seattable (
    seatno          INTEGER,
    ticket_ticketid NUMBER NOT NULL
);

CREATE TABLE seattable_audit (
    audit_id     INTEGER NOT NULL,
    operation_type  VARCHAR2(100),
    old_seatno   INTEGER,
    new_seatno   INTEGER,
    old_ticketid NUMBER,
    new_ticketid NUMBER,
    performed_by    VARCHAR2(200),
    operation_time  TIMESTAMP WITH LOCAL TIME ZONE,
    user_ip_address VARCHAR2(200),
    session_user    VARCHAR2(200),
    host_name       VARCHAR2(200)
);

ALTER TABLE seattable_audit ADD CONSTRAINT seattable_audit_pk PRIMARY KEY ( audit_id );

CREATE TABLE slottable (
    slotid             NUMBER NOT NULL,
    "date"             DATE,
    movietable_movieid NUMBER NOT NULL,
    halltable_hallid   NUMBER NOT NULL,
    slot               VARCHAR2(10),
    price              INTEGER
);

ALTER TABLE slottable ADD CONSTRAINT slottablev1_pk PRIMARY KEY ( slotid );

CREATE TABLE slottable_audit (
    audit_id        INTEGER NOT NULL,
    operation_type  VARCHAR2(100),
    slotid          NUMBER,
    old_date        DATE,
    new_date        DATE,
    old_movieid     NUMBER,
    new_movieid     NUMBER,
    old_hallid      NUMBER,
    new_hallid      NUMBER,
    old_slot        VARCHAR2(10),
    new_slot        VARCHAR2(10),
    old_price       INTEGER,
    new_price       INTEGER,
    performed_by    VARCHAR2(200),
    operation_time  TIMESTAMP WITH LOCAL TIME ZONE,
    user_ip_address VARCHAR2(200),
    session_user    VARCHAR2(200),
    host_name       VARCHAR2(200)
);

ALTER TABLE slottable_audit ADD CONSTRAINT slottable_audit_pk PRIMARY KEY ( audit_id );

CREATE TABLE ticket (
    ticketid         NUMBER NOT NULL,
    price            NUMBER,
    buyingdate       DATE,
    usertable_id     NUMBER NOT NULL,
    slottable_slotid NUMBER NOT NULL
);

ALTER TABLE ticket ADD CONSTRAINT ticketingtable_pk PRIMARY KEY ( ticketid );

CREATE TABLE ticket_audit (
    audit_id        INTEGER NOT NULL,
    operation_type  VARCHAR2(100),
    ticketid        NUMBER,
    old_price       NUMBER,
    new_price       NUMBER,
    old_buyingdate  DATE,
    new_buyingdate  DATE,
    old_id          NUMBER,
    new_id          NUMBER,
    old_slotid      NUMBER,
    new_slotid      NUMBER,
    
    performed_by    VARCHAR2(200),
    operation_time  TIMESTAMP WITH LOCAL TIME ZONE,
    user_ip_address VARCHAR2(200),
    session_user    VARCHAR2(200),
    host_name       VARCHAR2(200)
);

ALTER TABLE ticket_audit ADD CONSTRAINT ticket_audit_pk PRIMARY KEY ( audit_id );

CREATE TABLE usertable (
    id       NUMBER NOT NULL,
    name     VARCHAR2(50),
    email    VARCHAR2(70),
    username VARCHAR2(50),
    password VARCHAR2(256),
    usertype VARCHAR2(50)
);

ALTER TABLE usertable ADD CONSTRAINT usertable_pk PRIMARY KEY ( id );

ALTER TABLE seattable
    ADD CONSTRAINT seattable_ticket_fk FOREIGN KEY ( ticket_ticketid )
        REFERENCES ticket ( ticketid );

ALTER TABLE slottable
    ADD CONSTRAINT slottable_halltable_fk FOREIGN KEY ( halltable_hallid )
        REFERENCES halltable ( hallid );

ALTER TABLE slottable
    ADD CONSTRAINT slottable_movietable_fk FOREIGN KEY ( movietable_movieid )
        REFERENCES movietable ( movieid );

ALTER TABLE ticket
    ADD CONSTRAINT ticket_slottable_fk FOREIGN KEY ( slottable_slotid )
        REFERENCES slottable ( slotid );

ALTER TABLE ticket
    ADD CONSTRAINT ticket_usertable_fk FOREIGN KEY ( usertable_id )
        REFERENCES usertable ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0



